using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using OpenDeepWiki.EFCore;
using OpenDeepWiki.Entities;

namespace OpenDeepWiki.Services.Repositories;

public partial class RepositorySkillMarkdownBuilder(IGenerationWriteGuard? generationWriteGuard = null)
    : IRepositorySkillMarkdownBuilder
{
    private const int MaxSkillNameLength = 64;
    private static readonly Encoding ZipEntryEncoding = new UTF8Encoding(false);

    public async Task RefreshSkillMarkdownAsync(
        IContext context,
        Repository repository,
        RepositoryBranch branch,
        BranchLanguage language,
        CancellationToken cancellationToken = default,
        GenerationLeaseHandle? lease = null)
    {
        var catalogs = await context.DocCatalogs
            .AsNoTracking()
            .Where(catalog => catalog.BranchLanguageId == language.Id && !catalog.IsDeleted)
            .Include(catalog => catalog.DocFile)
            .OrderBy(catalog => catalog.Order)
            .ToListAsync(cancellationToken);

        var generatedAtUtc = DateTime.UtcNow;
        language.SkillMarkdown = BuildSkillMarkdown(repository, branch, language, catalogs, generatedAtUtc);
        language.SkillGeneratedAt = generatedAtUtc;
        language.UpdateTimestamp();
        context.BranchLanguages.Update(language);
        if (lease is null)
        {
            await context.SaveChangesAsync(cancellationToken);
        }
        else
        {
            await (generationWriteGuard ?? throw new InvalidOperationException("Generation write guard is not configured."))
                .SaveChangesAsync(context, lease, cancellationToken);
        }
    }

    public string BuildSkillMarkdown(
        Repository repository,
        RepositoryBranch branch,
        BranchLanguage language,
        IReadOnlyList<DocCatalog> catalogs,
        DateTime generatedAtUtc)
    {
        var skillName = BuildSkillName(repository.OrgName, repository.RepoName);
        var repositoryName = $"{repository.OrgName}/{repository.RepoName}";
        var description = $"Generated repository documentation skill for {repositoryName}.";
        var documentEntries = BuildDocumentEntries(catalogs, "references/docs");
        var builder = new StringBuilder();

        builder.AppendLine("---");
        builder.AppendLine($"name: {skillName}");
        builder.AppendLine($"description: \"{EscapeYaml(description)}\"");
        builder.AppendLine("license: MIT");
        builder.AppendLine("allowed-tools: \"\"");
        builder.AppendLine("metadata:");
        builder.AppendLine("  author: OpenDeepWiki");
        builder.AppendLine("  version: \"1.0.0\"");
        builder.AppendLine($"  repository: \"{EscapeYaml(repositoryName)}\"");
        builder.AppendLine($"  branch: \"{EscapeYaml(branch.BranchName)}\"");
        builder.AppendLine($"  language: \"{EscapeYaml(language.LanguageCode)}\"");
        builder.AppendLine($"  generatedAt: \"{generatedAtUtc:O}\"");
        builder.AppendLine("---");
        builder.AppendLine();
        builder.AppendLine($"# {repositoryName} Documentation Skill");
        builder.AppendLine();
        builder.AppendLine($"Use this skill when answering questions about the generated documentation for `{repositoryName}`.");
        builder.AppendLine("The source documentation is packaged under `references/docs/`.");
        builder.AppendLine();
        builder.AppendLine("## Repository Context");
        builder.AppendLine();
        builder.AppendLine($"- Repository: `{repositoryName}`");
        builder.AppendLine($"- Branch: `{branch.BranchName}`");
        builder.AppendLine($"- Documentation language: `{language.LanguageCode}`");
        builder.AppendLine("- Generated by: OpenDeepWiki");
        builder.AppendLine();
        builder.AppendLine("## How To Use");
        builder.AppendLine();
        builder.AppendLine("1. Start from the document index below to find the relevant generated wiki page.");
        builder.AppendLine("2. Read the linked Markdown files in `references/docs/` before answering repository-specific questions.");
        builder.AppendLine("3. Treat the packaged documents as generated documentation, not as a replacement for the original source code.");
        builder.AppendLine();
        builder.AppendLine("## Document Index");
        builder.AppendLine();

        if (documentEntries.Count == 0)
        {
            builder.AppendLine("No generated documentation files were available when this skill descriptor was created.");
        }
        else
        {
            foreach (var entry in documentEntries)
            {
                var indent = new string(' ', entry.Depth * 2);
                builder.AppendLine($"{indent}- [{EscapeMarkdownLinkText(entry.Title)}]({EscapeMarkdownLinkTarget(entry.RelativePath)})");
            }
        }

        return builder.ToString();
    }

    public async Task AddDocumentsToArchiveAsync(
        ZipArchive archive,
        IReadOnlyList<DocCatalog> catalogs,
        string rootPath,
        CancellationToken cancellationToken = default)
    {
        AddDirectoryEntry(archive, "references");
        AddDirectoryEntry(archive, rootPath);

        var entries = BuildDocumentEntries(catalogs, rootPath);
        foreach (var entry in entries)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entry.Catalog.DocFile is null)
            {
                continue;
            }

            var zipEntry = archive.CreateEntry(entry.RelativePath);
            await using var entryStream = zipEntry.Open();
            await using var writer = new StreamWriter(entryStream, ZipEntryEncoding);
            await writer.WriteAsync(entry.Catalog.DocFile.Content.AsMemory(), cancellationToken);
        }

        foreach (var directory in BuildDirectoryEntries(catalogs, rootPath))
        {
            AddDirectoryEntry(archive, directory);
        }
    }

    internal static string BuildSkillName(string owner, string repo)
    {
        var rawName = $"{owner}-{repo}";
        var normalized = SkillNameInvalidCharactersRegex()
            .Replace(rawName.ToLowerInvariant(), "-")
            .Trim('-');

        if (string.IsNullOrWhiteSpace(normalized))
        {
            normalized = "repository-skill";
        }

        if (normalized.Length <= MaxSkillNameLength)
        {
            return normalized;
        }

        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(rawName)))[..8]
            .ToLowerInvariant();
        var prefixLength = MaxSkillNameLength - hash.Length - 1;
        var prefix = normalized[..Math.Min(prefixLength, normalized.Length)].Trim('-');
        return string.IsNullOrEmpty(prefix)
            ? $"repo-{hash}"
            : $"{prefix}-{hash}";
    }

    private static List<SkillDocumentEntry> BuildDocumentEntries(
        IReadOnlyList<DocCatalog> catalogs,
        string rootPath)
    {
        var results = new List<SkillDocumentEntry>();
        AddDocumentEntries(catalogs, null, rootPath.Trim('/'), 0, results);
        return results;
    }

    private static void AddDocumentEntries(
        IReadOnlyList<DocCatalog> catalogs,
        string? parentCatalogId,
        string parentZipPath,
        int depth,
        List<SkillDocumentEntry> results)
    {
        var currentLevelItems = catalogs
            .Where(catalog => catalog.ParentId == parentCatalogId)
            .OrderBy(catalog => catalog.Order)
            .ToList();

        var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var catalog in currentLevelItems)
        {
            var itemName = EnsureUniqueName(SanitizeZipNameSegment(catalog.Title), usedNames);
            var currentPath = CombineZipPath(parentZipPath, itemName);
            var hasChildren = catalogs.Any(child => child.ParentId == catalog.Id);

            if (!hasChildren && !string.IsNullOrEmpty(catalog.DocFileId))
            {
                results.Add(new SkillDocumentEntry(
                    catalog,
                    catalog.Title,
                    $"{currentPath}.md",
                    depth));
            }

            AddDocumentEntries(catalogs, catalog.Id, currentPath, depth + 1, results);
        }
    }

    private static List<string> BuildDirectoryEntries(IReadOnlyList<DocCatalog> catalogs, string rootPath)
    {
        var directories = new List<string>();
        AddDirectoryEntries(catalogs, null, rootPath.Trim('/'), directories);
        return directories;
    }

    private static void AddDirectoryEntries(
        IReadOnlyList<DocCatalog> catalogs,
        string? parentCatalogId,
        string parentZipPath,
        List<string> directories)
    {
        var currentLevelItems = catalogs
            .Where(catalog => catalog.ParentId == parentCatalogId)
            .OrderBy(catalog => catalog.Order)
            .ToList();

        var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var catalog in currentLevelItems)
        {
            var itemName = EnsureUniqueName(SanitizeZipNameSegment(catalog.Title), usedNames);
            var currentPath = CombineZipPath(parentZipPath, itemName);
            if (catalogs.Any(child => child.ParentId == catalog.Id))
            {
                directories.Add(currentPath);
                AddDirectoryEntries(catalogs, catalog.Id, currentPath, directories);
            }
        }
    }

    private static void AddDirectoryEntry(ZipArchive archive, string path)
    {
        var normalized = path.Trim('/');
        if (string.IsNullOrEmpty(normalized))
        {
            return;
        }

        archive.CreateEntry(normalized + "/");
    }

    private static string CombineZipPath(string parentZipPath, string entryName)
    {
        return string.IsNullOrEmpty(parentZipPath)
            ? entryName
            : $"{parentZipPath}/{entryName}";
    }

    private static string SanitizeZipNameSegment(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "untitled";
        }

        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new string(value
            .Trim()
            .Select(ch => invalidChars.Contains(ch) ? '_' : ch)
            .ToArray());

        sanitized = sanitized.TrimEnd('.', ' ');

        return string.IsNullOrWhiteSpace(sanitized)
            ? "untitled"
            : sanitized;
    }

    private static string EnsureUniqueName(string baseName, ISet<string> usedNames)
    {
        if (usedNames.Add(baseName))
        {
            return baseName;
        }

        for (var index = 2;; index++)
        {
            var candidate = $"{baseName} ({index})";
            if (usedNames.Add(candidate))
            {
                return candidate;
            }
        }
    }

    private static string EscapeYaml(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", " ")
            .Replace("\n", " ");
    }

    private static string EscapeMarkdownLinkText(string value)
    {
        return value.Replace("[", "\\[").Replace("]", "\\]");
    }

    private static string EscapeMarkdownLinkTarget(string value)
    {
        return value.Replace(" ", "%20");
    }

    [GeneratedRegex("[^a-z0-9]+", RegexOptions.Compiled)]
    private static partial Regex SkillNameInvalidCharactersRegex();

    private sealed record SkillDocumentEntry(
        DocCatalog Catalog,
        string Title,
        string RelativePath,
        int Depth);
}
